language: python
python:
  - "2.7"
  - "3.5"
before_install:
  - sudo apt-get -qq update
  - make sysdeps
  - make pydeps
install:
  - pip install --timeout=30 pep8
  - pip install --timeout=30 pyflakes
  - pip install --timeout=30 -q -e .
before_script:
  - make check
script:
  - make test
