build: false

environment:
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.x"
      PYTHON_ARCH: "32"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "%PYTHON%/python.exe -m pip install -U -r requirements.txt"
  - "%PYTHON%/python.exe setup.py install"
  - "%PYTHON%/python.exe tests.py"

skip_commits:
  message: skip-ci
